apiVersion: apps/v1
kind: Pod
metadata: 
 name: httpd-frontend 
 labels: 
   app: myapp
   name: frontend

 spec: 
     containers: 
        - name: httpd-frontend 
          image: httpd:2.4-alpine
