apiVersion: apps/v1
kind: Deployment
metadata: 
   name: worker-app-deploy
   labels: 
     name: worker-app-deploy
     app: demo-worker-app
spec:
   replicas: 1
   selector:
      matchLabels:
         name: worker-app-deploy
         app: demo-worker-app
   template: #from here pod is starting
    metadata:
     name: worker-app
     labels:
       name: worker-app
       app: demo-boting-app
    spec:
     containers:
      - name: worker-app
        image: kodekloud/examplevotingapp_worker:v1
